overrides:
  braces@<2.3.1: '>=2.3.1'
  braces@<3.0.3: '>=3.0.3'
  cross-spawn@<6.0.6: '>=6.0.6'
  got@<11.8.5: '>=11.8.5'
  micromatch@<4.0.8: '>=4.0.8'
  postcss@<7.0.36: '>=7.0.36'
  postcss@<8.4.31: '>=8.4.31'
  trim-newlines@<3.0.1: '>=3.0.1'
  trim@<0.0.3: '>=0.0.3'
